services:
  db:
    image: postgres:latest
    container_name: kanban_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kanban_user
      POSTGRES_PASSWORD: kanban_password
      POSTGRES_DB: kanban_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/migrations:/migrations

  go_backend:
    build:
      context: ./go_backend
    container_name: kanban_go_backend
    ports:
      - "9082:9080"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://kanban_user:kanban_password@db:5432/kanban_db"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9080 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  python_backend:
    build:
      context: ./python_backend
    container_name: kanban_python_backend
    ports:
      - "9083:9080"
    depends_on:
      - db
    volumes:
      - ./python_backend:/app
    environment:
      FLASK_ENV: development
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9080 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: ./frontend
    container_name: kanban_frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "9081:80"

  proxy:
    image: nginx:latest
    container_name: kanban_proxy
    ports:
      - "9080:9080"
    depends_on:
      - go_backend
      - python_backend
    volumes:
      - ./proxy/nginx.config:/etc/nginx/nginx.conf


volumes:
  db_data: