version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: kanban_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kanban_user
      POSTGRES_PASSWORD: kanban_password
      POSTGRES_DB: kanban_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/migrations:/migrations
  backend:
    build:
      context: ./backend
    container_name: kanban_backend
    ports:
      - "9080:9080"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://kanban_user:kanban_password@db:5432/kanban_db"
  frontend:
    build:
      context: ./frontend
    container_name: kanban_frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "9081:80"
    depends_on:
      - backend

volumes:
  db_data: