version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: kanban_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kanban_user
      POSTGRES_PASSWORD: kanban_password
      POSTGRES_DB: kanban_db
    volumes:
      - db_data:/var/lib/postgresql/data
       - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:

